
services:
  sso-app:
    container_name: sso-app
    depends_on: [ sso-postgres ]
    build:
      context: .
      dockerfile: .docker/sso-app.Dockerfile
    ports:
      - "8080:8080"
    profiles:
      - infra
  sso-postgres:
    container_name: sso-postgres
    image: postgres:15.3
    environment:
      POSTGRES_DB: "sso-postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    profiles:
      - infra
